In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Data/cleaned_data.csv")

In [3]:
df.head()

,title,price,bedrooms,has_maid_room,bathrooms,area_sqm,property_type,available_from,location,amenities,...,amenity_private_garden,amenity_private_pool,amenity_security,amenity_shared_gym,amenity_shared_pool,amenity_shared_spa,amenity_study,amenity_view_of_landmark,amenity_view_of_water,amenity_walk-in_closet
0,A Full Sea view chalet 3BR for sale in north c...,16400000,3,True,3,1401507,Chalet,2026-04-30,"June, Ras Al Hekma, North Coast","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
1,Sea View Chalet 1BR In Fouka Bay Fully Finished,10500000,1,True,1,50538,Chalet,2026-06-21,"Fouka Bay, Qesm Marsa Matrouh, North Coast","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
2,chalet 3bed ready to move prime location old p...,17500000,3,True,3,1441550,Chalet,2026-06-04,"Marassi, Sidi Abdel Rahman, North Coast","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
3,apartment 2bed for sale ready to move old price !,5000000,2,True,2,1081163,Apartment,2026-06-16,"Zed East, 5th Settlement Compounds, The 5th Se...","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
4,First Row Armani Standalone Villa 5BR with 5% DP!,250000000,5,True,6,3253498,Villa,2026-06-22,"Silver Sands, Qesm Marsa Matrouh, North Coast","Partly furnished, Balcony, Built in Wardrobes,...",...,1,1,0,0,0,0,1,0,1,0

In [4]:
df.shape

(919, 33)

In [5]:
df.columns

Index(['title', 'price', 'bedrooms', 'has_maid_room', 'bathrooms', 'area_sqm',
       'property_type', 'available_from', 'location', 'amenities', 'region',
       'sub_area', 'furnishing_status', 'amenities_no_furnishing',
       'amenities_clean_list', 'amenity_balcony', 'amenity_built_in_wardrobes',
       'amenity_central_a_c', 'amenity_children's_pool',
       'amenity_covered_parking', 'amenity_kitchen_appliances',
       'amenity_lobby_in_building', 'amenity_maids_room',
       'amenity_private_garden', 'amenity_private_pool', 'amenity_security',
       'amenity_shared_gym', 'amenity_shared_pool', 'amenity_shared_spa',
       'amenity_study', 'amenity_view_of_landmark', 'amenity_view_of_water',
       'amenity_walk-in_closet'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       919 non-null    str
 1   price                       919 non-null    int64
 2   bedrooms                    919 non-null    int64
 3   has_maid_room               919 non-null    bool
 4   bathrooms                   919 non-null    int64
 5   area_sqm                    919 non-null    int64
 6   property_type               919 non-null    str
 7   available_from              919 non-null    str
 8   location                    919 non-null    str
 9   amenities                   919 non-null    str
 10  region                      919 non-null    str
 11  sub_area                    919 non-null    str
 12  furnishing_status           919 non-null    str
 13  amenities_no_furnishing     919 non-null    str
 14  amenities_clean_list        919 non-null    str
 15  amenity_balcony             919 non-null    int64
 16  amenity_built_in_wardrobes  919 non-null    int64
 17  amenity_central_a_c         919 non-null    int64
 18  amenity_children's_pool     919 non-null    int64
 19  amenity_covered_parking     919 non-null    int64
 20  amenity_kitchen_appliances  919 non-null    int64
 21  amenity_lobby_in_building   919 non-null    int64
 22  amenity_maids_room          919 non-null    int64
 23  amenity_private_garden      919 non-null    int64
 24  amenity_private_pool        919 non-null    int64
 25  amenity_security            919 non-null    int64
 26  amenity_shared_gym          919 non-null    int64
 27  amenity_shared_pool         919 non-null    int64
 28  amenity_shared_spa          919 non-null    int64
 29  amenity_study               919 non-null    int64
 30  amenity_view_of_landmark    919 non-null    int64
 31  amenity_view_of_water       919 non-null    int64
 32  amenity_walk-in_closet      919 non-null    int64
dtypes: bool(1), int64(22), str(10)
memory usage: 230.8 KB

In [7]:
df["available_from"] = pd.to_datetime(df["available_from"])

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       919 non-null    str
 1   price                       919 non-null    int64
 2   bedrooms                    919 non-null    int64
 3   has_maid_room               919 non-null    bool
 4   bathrooms                   919 non-null    int64
 5   area_sqm                    919 non-null    int64
 6   property_type               919 non-null    str
 7   available_from              919 non-null    datetime64[us]
 8   location                    919 non-null    str
 9   amenities                   919 non-null    str
 10  region                      919 non-null    str
 11  sub_area                    919 non-null    str
 12  furnishing_status           919 non-null    str
 13  amenities_no_furnishing     919 non-null    str
 14  amenities_clean_list        919 non-null    str
 15  amenity_balcony             919 non-null    int64
 16  amenity_built_in_wardrobes  919 non-null    int64
 17  amenity_central_a_c         919 non-null    int64
 18  amenity_children's_pool     919 non-null    int64
 19  amenity_covered_parking     919 non-null    int64
 20  amenity_kitchen_appliances  919 non-null    int64
 21  amenity_lobby_in_building   919 non-null    int64
 22  amenity_maids_room          919 non-null    int64
 23  amenity_private_garden      919 non-null    int64
 24  amenity_private_pool        919 non-null    int64
 25  amenity_security            919 non-null    int64
 26  amenity_shared_gym          919 non-null    int64
 27  amenity_shared_pool         919 non-null    int64
 28  amenity_shared_spa          919 non-null    int64
 29  amenity_study               919 non-null    int64
 30  amenity_view_of_landmark    919 non-null    int64
 31  amenity_view_of_water       919 non-null    int64
 32  amenity_walk-in_closet      919 non-null    int64
dtypes: bool(1), datetime64[us](1), int64(22), str(9)
memory usage: 230.8 KB

In [9]:
df["available_year"] = df["available_from"].dt.year
df["available_month"] = df["available_from"].dt.month
df["available_day"] = df["available_from"].dt.day

In [10]:
df[["available_from", "available_year", "available_month", "available_day"]].head()

  available_from  available_year  available_month  available_day
0     2026-04-30            2026                4             30
1     2026-06-21            2026                6             21
2     2026-06-04            2026                6              4
3     2026-06-16            2026                6             16
4     2026-06-22            2026                6             22

In [11]:
categorical_cols = [
    "property_type",
    "region",
    "sub_area",
    "furnishing_status"
]

for col in categorical_cols:
    df[col] = df[col].astype("category")

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       919 non-null    str
 1   price                       919 non-null    int64
 2   bedrooms                    919 non-null    int64
 3   has_maid_room               919 non-null    bool
 4   bathrooms                   919 non-null    int64
 5   area_sqm                    919 non-null    int64
 6   property_type               919 non-null    category
 7   available_from              919 non-null    datetime64[us]
 8   location                    919 non-null    str
 9   amenities                   919 non-null    str
 10  region                      919 non-null    category
 11  sub_area                    919 non-null    category
 12  furnishing_status           919 non-null    category
 13  amenities_no_furnishing     919 non-null    str
 14  amenities_clean_list        919 non-null    str
 15  amenity_balcony             919 non-null    int64
 16  amenity_built_in_wardrobes  919 non-null    int64
 17  amenity_central_a_c         919 non-null    int64
 18  amenity_children's_pool     919 non-null    int64
 19  amenity_covered_parking     919 non-null    int64
 20  amenity_kitchen_appliances  919 non-null    int64
 21  amenity_lobby_in_building   919 non-null    int64
 22  amenity_maids_room          919 non-null    int64
 23  amenity_private_garden      919 non-null    int64
 24  amenity_private_pool        919 non-null    int64
 25  amenity_security            919 non-null    int64
 26  amenity_shared_gym          919 non-null    int64
 27  amenity_shared_pool         919 non-null    int64
 28  amenity_shared_spa          919 non-null    int64
 29  amenity_study               919 non-null    int64
 30  amenity_view_of_landmark    919 non-null    int64
 31  amenity_view_of_water       919 non-null    int64
 32  amenity_walk-in_closet      919 non-null    int64
 33  available_year              919 non-null    int32
 34  available_month             919 non-null    int32
 35  available_day               919 non-null    int32
dtypes: bool(1), category(4), datetime64[us](1), int32(3), int64(22), str(5)
memory usage: 217.4 KB

In [13]:
df["price_per_sqm"] = df["price"] / df["area_sqm"]

In [14]:
df[["price", "area_sqm", "price_per_sqm"]].head()

       price  area_sqm  price_per_sqm
0   16400000   1401507      11.701690
1   10500000     50538     207.764454
2   17500000   1441550      12.139711
3    5000000   1081163       4.624650
4  250000000   3253498      76.840373

In [15]:
df["area_sqm"].describe()

count    9.190000e+02
mean     3.984422e+06
std      2.224007e+07
min      3.840900e+04
25%      1.271367e+06
50%      1.641765e+06
75%      2.307481e+06
max      4.000431e+08
Name: area_sqm, dtype: float64

In [16]:
df["area_sqm"].sort_values().tail(20)

171      7207750
432      7407965
64       7488051
710      7858450
214      7908503
502      8038643
456      8409042
202      8809472
207      9009688
172     93110021
200     95010226
232    110011840
668    113512217
669    113512217
169    119012809
142    120012917
158    140015069
170    200021528
778    400043056
777    400043056
Name: area_sqm, dtype: int64