# Estate Miner Preprocessing

## Notebook Flow

- Load the cleaned dataset and inspect its structure.
- Convert and standardize key columns for analysis.
- Create derived features that summarize price, space, and amenities.

In [2]:
import numpy as np
import pandas as pd

## 1. Load and Inspect the Dataset

Start by loading the cleaned listings data and reviewing its basic structure, sample rows, and column layout.

In [3]:
df = pd.read_csv("Data/cleaned_data.csv")

In [4]:
df.head()

,title,price,bedrooms,has_maid_room,bathrooms,area_sqm,property_type,available_from,location,amenities,...,amenity_private_garden,amenity_private_pool,amenity_security,amenity_shared_gym,amenity_shared_pool,amenity_shared_spa,amenity_study,amenity_view_of_landmark,amenity_view_of_water,amenity_walk-in_closet
0,A Full Sea view chalet 3BR for sale in north c...,16400000,3,True,3,140,Chalet,2026-04-30,"June, Ras Al Hekma, North Coast","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
1,Sea View Chalet 1BR In Fouka Bay Fully Finished,10500000,1,True,1,50,Chalet,2026-06-21,"Fouka Bay, Qesm Marsa Matrouh, North Coast","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
2,chalet 3bed ready to move prime location old p...,17500000,3,True,3,144,Chalet,2026-06-04,"Marassi, Sidi Abdel Rahman, North Coast","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
3,apartment 2bed for sale ready to move old price !,5000000,2,True,2,108,Apartment,2026-06-16,"Zed East, 5th Settlement Compounds, The 5th Se...","Unfurnished, Balcony, Built in Wardrobes, Cent...",...,1,1,0,0,1,0,0,0,0,0
4,First Row Armani Standalone Villa 5BR with 5% DP!,250000000,5,True,6,325,Villa,2026-06-22,"Silver Sands, Qesm Marsa Matrouh, North Coast","Partly furnished, Balcony, Built in Wardrobes,...",...,1,1,0,0,0,0,1,0,1,0

In [5]:
df.shape

(919, 34)

In [6]:
df.columns

Index(['title', 'price', 'bedrooms', 'has_maid_room', 'bathrooms', 'area_sqm',
       'property_type', 'available_from', 'location', 'amenities', 'area_sqft',
       'region', 'sub_area', 'furnishing_status', 'amenities_no_furnishing',
       'amenities_clean_list', 'amenity_balcony', 'amenity_built_in_wardrobes',
       'amenity_central_a_c', 'amenity_children's_pool',
       'amenity_covered_parking', 'amenity_kitchen_appliances',
       'amenity_lobby_in_building', 'amenity_maids_room',
       'amenity_private_garden', 'amenity_private_pool', 'amenity_security',
       'amenity_shared_gym', 'amenity_shared_pool', 'amenity_shared_spa',
       'amenity_study', 'amenity_view_of_landmark', 'amenity_view_of_water',
       'amenity_walk-in_closet'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       919 non-null    str
 1   price                       919 non-null    int64
 2   bedrooms                    919 non-null    int64
 3   has_maid_room               919 non-null    bool
 4   bathrooms                   919 non-null    int64
 5   area_sqm                    919 non-null    int64
 6   property_type               919 non-null    str
 7   available_from              919 non-null    str
 8   location                    919 non-null    str
 9   amenities                   919 non-null    str
 10  area_sqft                   919 non-null    int64
 11  region                      919 non-null    str
 12  sub_area                    919 non-null    str
 13  furnishing_status           919 non-null    str
 14  amenities_no_furnishing     919 non-null    str
 15  amenities_clean_list        919 non-null    str
 16  amenity_balcony             919 non-null    int64
 17  amenity_built_in_wardrobes  919 non-null    int64
 18  amenity_central_a_c         919 non-null    int64
 19  amenity_children's_pool     919 non-null    int64
 20  amenity_covered_parking     919 non-null    int64
 21  amenity_kitchen_appliances  919 non-null    int64
 22  amenity_lobby_in_building   919 non-null    int64
 23  amenity_maids_room          919 non-null    int64
 24  amenity_private_garden      919 non-null    int64
 25  amenity_private_pool        919 non-null    int64
 26  amenity_security            919 non-null    int64
 27  amenity_shared_gym          919 non-null    int64
 28  amenity_shared_pool         919 non-null    int64
 29  amenity_shared_spa          919 non-null    int64
 30  amenity_study               919 non-null    int64
 31  amenity_view_of_landmark    919 non-null    int64
 32  amenity_view_of_water       919 non-null    int64
 33  amenity_walk-in_closet      919 non-null    int64
dtypes: bool(1), int64(23), str(10)
memory usage: 238.0 KB

In [8]:
df["available_from"] = pd.to_datetime(df["available_from"])

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       919 non-null    str
 1   price                       919 non-null    int64
 2   bedrooms                    919 non-null    int64
 3   has_maid_room               919 non-null    bool
 4   bathrooms                   919 non-null    int64
 5   area_sqm                    919 non-null    int64
 6   property_type               919 non-null    str
 7   available_from              919 non-null    datetime64[us]
 8   location                    919 non-null    str
 9   amenities                   919 non-null    str
 10  area_sqft                   919 non-null    int64
 11  region                      919 non-null    str
 12  sub_area                    919 non-null    str
 13  furnishing_status           919 non-null    str
 14  amenities_no_furnishing     919 non-null    str
 15  amenities_clean_list        919 non-null    str
 16  amenity_balcony             919 non-null    int64
 17  amenity_built_in_wardrobes  919 non-null    int64
 18  amenity_central_a_c         919 non-null    int64
 19  amenity_children's_pool     919 non-null    int64
 20  amenity_covered_parking     919 non-null    int64
 21  amenity_kitchen_appliances  919 non-null    int64
 22  amenity_lobby_in_building   919 non-null    int64
 23  amenity_maids_room          919 non-null    int64
 24  amenity_private_garden      919 non-null    int64
 25  amenity_private_pool        919 non-null    int64
 26  amenity_security            919 non-null    int64
 27  amenity_shared_gym          919 non-null    int64
 28  amenity_shared_pool         919 non-null    int64
 29  amenity_shared_spa          919 non-null    int64
 30  amenity_study               919 non-null    int64
 31  amenity_view_of_landmark    919 non-null    int64
 32  amenity_view_of_water       919 non-null    int64
 33  amenity_walk-in_closet      919 non-null    int64
dtypes: bool(1), datetime64[us](1), int64(23), str(9)
memory usage: 238.0 KB

## 2. Create Date-Based Features

Convert the listing date into a datetime field and extract useful calendar components for analysis.

In [10]:
df["available_year"] = df["available_from"].dt.year
df["available_month"] = df["available_from"].dt.month
df["available_day"] = df["available_from"].dt.day

In [11]:
df[["available_from", "available_year", "available_month", "available_day"]].head()

  available_from  available_year  available_month  available_day
0     2026-04-30            2026                4             30
1     2026-06-21            2026                6             21
2     2026-06-04            2026                6              4
3     2026-06-16            2026                6             16
4     2026-06-22            2026                6             22

In [12]:
categorical_cols = [
    "property_type",
    "region",
    "sub_area",
    "furnishing_status"
]

for col in categorical_cols:
    df[col] = df[col].astype("category")

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 37 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       919 non-null    str
 1   price                       919 non-null    int64
 2   bedrooms                    919 non-null    int64
 3   has_maid_room               919 non-null    bool
 4   bathrooms                   919 non-null    int64
 5   area_sqm                    919 non-null    int64
 6   property_type               919 non-null    category
 7   available_from              919 non-null    datetime64[us]
 8   location                    919 non-null    str
 9   amenities                   919 non-null    str
 10  area_sqft                   919 non-null    int64
 11  region                      919 non-null    category
 12  sub_area                    919 non-null    category
 13  furnishing_status           919 non-null    category
 14  amenities_no_furnishing     919 non-null    str
 15  amenities_clean_list        919 non-null    str
 16  amenity_balcony             919 non-null    int64
 17  amenity_built_in_wardrobes  919 non-null    int64
 18  amenity_central_a_c         919 non-null    int64
 19  amenity_children's_pool     919 non-null    int64
 20  amenity_covered_parking     919 non-null    int64
 21  amenity_kitchen_appliances  919 non-null    int64
 22  amenity_lobby_in_building   919 non-null    int64
 23  amenity_maids_room          919 non-null    int64
 24  amenity_private_garden      919 non-null    int64
 25  amenity_private_pool        919 non-null    int64
 26  amenity_security            919 non-null    int64
 27  amenity_shared_gym          919 non-null    int64
 28  amenity_shared_pool         919 non-null    int64
 29  amenity_shared_spa          919 non-null    int64
 30  amenity_study               919 non-null    int64
 31  amenity_view_of_landmark    919 non-null    int64
 32  amenity_view_of_water       919 non-null    int64
 33  amenity_walk-in_closet      919 non-null    int64
 34  available_year              919 non-null    int32
 35  available_month             919 non-null    int32
 36  available_day               919 non-null    int32
dtypes: bool(1), category(4), datetime64[us](1), int32(3), int64(23), str(5)
memory usage: 224.6 KB

## 3. Standardize Categorical Columns

Cast the main categorical fields to the category dtype to reduce memory usage and make the data easier to work with.

In [14]:
df["price_per_sqm"] = df["price"] / df["area_sqm"]

In [15]:
df[["price", "area_sqm", "price_per_sqm"]].head()

       price  area_sqm  price_per_sqm
0   16400000       140  117142.857143
1   10500000        50  210000.000000
2   17500000       144  121527.777778
3    5000000       108   46296.296296
4  250000000       325  769230.769231

## 4. Engineer Pricing and Size Features

Create ratio-based features that normalize price and area by bedrooms, bathrooms, and floor area.

In [18]:
amenity_cols = [col for col in df.columns if col.startswith("amenity_")]

df["amenities_count"] = df[amenity_cols].sum(axis=1)

In [21]:
df[["amenities_count"]].head()

   amenities_count
0                9
1                9
2                9
3                9
4                9

In [22]:
df["amenities_count"].value_counts().sort_index()

amenities_count
1       1
2       8
3       4
5      13
6       3
7       4
8       8
9     807
10     71
Name: count, dtype: int64

In [23]:
df[amenity_cols].sum().sort_values(ascending=False)

amenity_balcony               885
amenity_covered_parking       866
amenity_central_a_c           814
amenity_maids_room            786
amenity_built_in_wardrobes    782
amenity_private_garden        781
amenity_shared_pool           777
amenity_kitchen_appliances    762
amenity_private_pool          744
amenity_study                 310
amenity_view_of_water         187
amenity_security              173
amenity_shared_spa            108
amenity_shared_gym             85
amenity_walk-in_closet         45
amenity_view_of_landmark       32
amenity_lobby_in_building      20
amenity_children's_pool        20
dtype: int64

## 5. Build Amenity and Room Features

Summarize available amenities and derive room-based indicators that help compare listings at a glance.

In [24]:
df["total_rooms"] = df["bedrooms"] + df["bathrooms"]

In [25]:
df[["bedrooms", "bathrooms", "total_rooms"]].head()

   bedrooms  bathrooms  total_rooms
0         3          3            6
1         1          1            2
2         3          3            6
3         2          2            4
4         5          6           11

In [26]:
(df["bedrooms"] == 0).sum()

np.int64(0)

In [27]:
df["price_per_bedroom"] = df["price"] / df["bedrooms"]

In [28]:
df[["price", "bedrooms", "price_per_bedroom"]].head()

       price  bedrooms  price_per_bedroom
0   16400000         3       5.466667e+06
1   10500000         1       1.050000e+07
2   17500000         3       5.833333e+06
3    5000000         2       2.500000e+06
4  250000000         5       5.000000e+07

In [29]:
(df["bathrooms"] == 0).sum()

np.int64(0)

In [30]:
df["price_per_bathroom"] = df["price"] / df["bathrooms"]

In [31]:
df[["price", "bathrooms", "price_per_bathroom"]].head()

       price  bathrooms  price_per_bathroom
0   16400000          3        5.466667e+06
1   10500000          1        1.050000e+07
2   17500000          3        5.833333e+06
3    5000000          2        2.500000e+06
4  250000000          6        4.166667e+07

In [32]:
df["area_per_bedroom"] = df["area_sqm"] / df["bedrooms"]

In [33]:
df[["area_sqm", "bedrooms", "area_per_bedroom"]].head()

   area_sqm  bedrooms  area_per_bedroom
0       140         3         46.666667
1        50         1         50.000000
2       144         3         48.000000
3       108         2         54.000000
4       325         5         65.000000

In [34]:
df["area_per_bathroom"] = df["area_sqm"] / df["bathrooms"]

In [35]:
df[["area_sqm", "bathrooms", "area_per_bathroom"]].head()

   area_sqm  bathrooms  area_per_bathroom
0       140          3          46.666667
1        50          1          50.000000
2       144          3          48.000000
3       108          2          54.000000
4       325          6          54.166667

In [37]:
df["amenities_per_room"] = df["amenities_count"] / df["total_rooms"]

In [38]:
df[["amenities_count", "total_rooms", "amenities_per_room"]].head()

   amenities_count  total_rooms  amenities_per_room
0                9            6            1.500000
1                9            2            4.500000
2                9            6            1.500000
3                9            4            2.250000
4                9           11            0.818182

In [39]:
new_features = [
    "price_per_sqm",
    "amenities_count",
    "total_rooms",
    "price_per_bedroom",
    "price_per_bathroom",
    "area_per_bedroom",
    "area_per_bathroom",
    "amenities_per_room"
]

df[new_features].head()

,price_per_sqm,amenities_count,total_rooms,price_per_bedroom,price_per_bathroom,area_per_bedroom,area_per_bathroom,amenities_per_room
0,117142.857143,9,6,5.466667e+06,5.466667e+06,46.666667,46.666667,1.500000
1,210000.000000,9,2,1.050000e+07,1.050000e+07,50.000000,50.000000,4.500000
2,121527.777778,9,6,5.833333e+06,5.833333e+06,48.000000,48.000000,1.500000
3,46296.296296,9,4,2.500000e+06,2.500000e+06,54.000000,54.000000,2.250000
4,769230.769231,9,11,5.000000e+07,4.166667e+07,65.000000,54.166667,0.818182

## 6. Run Final Validation Checks

Review null values, duplicates, and descriptive statistics to confirm the dataset is ready for downstream modeling or analysis.

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       919 non-null    str
 1   price                       919 non-null    int64
 2   bedrooms                    919 non-null    int64
 3   has_maid_room               919 non-null    bool
 4   bathrooms                   919 non-null    int64
 5   area_sqm                    919 non-null    int64
 6   property_type               919 non-null    category
 7   available_from              919 non-null    datetime64[us]
 8   location                    919 non-null    str
 9   amenities                   919 non-null    str
 10  area_sqft                   919 non-null    int64
 11  region                      919 non-null    category
 12  sub_area                    919 non-null    category
 13  furnishing_status           919 non-null    category
 14  amenities_no_furnishing     919 non-null    str
 15  amenities_clean_list        919 non-null    str
 16  amenity_balcony             919 non-null    int64
 17  amenity_built_in_wardrobes  919 non-null    int64
 18  amenity_central_a_c         919 non-null    int64
 19  amenity_children's_pool     919 non-null    int64
 20  amenity_covered_parking     919 non-null    int64
 21  amenity_kitchen_appliances  919 non-null    int64
 22  amenity_lobby_in_building   919 non-null    int64
 23  amenity_maids_room          919 non-null    int64
 24  amenity_private_garden      919 non-null    int64
 25  amenity_private_pool        919 non-null    int64
 26  amenity_security            919 non-null    int64
 27  amenity_shared_gym          919 non-null    int64
 28  amenity_shared_pool         919 non-null    int64
 29  amenity_shared_spa          919 non-null    int64
 30  amenity_study               919 non-null    int64
 31  amenity_view_of_landmark    919 non-null    int64
 32  amenity_view_of_water       919 non-null    int64
 33  amenity_walk-in_closet      919 non-null    int64
 34  available_year              919 non-null    int32
 35  available_month             919 non-null    int32
 36  available_day               919 non-null    int32
 37  price_per_sqm               919 non-null    float64
 38  amenities_count             919 non-null    int64
 39  total_rooms                 919 non-null    int64
 40  price_per_bedroom           919 non-null    float64
 41  price_per_bathroom          919 non-null    float64
 42  area_per_bedroom            919 non-null    float64
 43  area_per_bathroom           919 non-null    float64
 44  amenities_per_room          919 non-null    float64
dtypes: bool(1), category(4), datetime64[us](1), float64(6), int32(3), int64(25), str(5)
memory usage: 282.1 KB

In [41]:
df.isnull().sum()

title                         0
price                         0
bedrooms                      0
has_maid_room                 0
bathrooms                     0
area_sqm                      0
property_type                 0
available_from                0
location                      0
amenities                     0
area_sqft                     0
region                        0
sub_area                      0
furnishing_status             0
amenities_no_furnishing       0
amenities_clean_list          0
amenity_balcony               0
amenity_built_in_wardrobes    0
amenity_central_a_c           0
amenity_children's_pool       0
amenity_covered_parking       0
amenity_kitchen_appliances    0
amenity_lobby_in_building     0
amenity_maids_room            0
amenity_private_garden        0
amenity_private_pool          0
amenity_security              0
amenity_shared_gym            0
amenity_shared_pool           0
amenity_shared_spa            0
amenity_study                 0
amenity_view_of_landmark      0
amenity_view_of_water         0
amenity_walk-in_closet        0
available_year                0
available_month               0
available_day                 0
price_per_sqm                 0
amenities_count               0
total_rooms                   0
price_per_bedroom             0
price_per_bathroom            0
area_per_bedroom              0
area_per_bathroom             0
amenities_per_room            0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
price,919.0,28330536.05876,3300000.0,12300000.0,17000000.0,25000000.0,900000000.0,54200714.543506
bedrooms,919.0,3.022851,1.0,2.0,3.0,4.0,7.0,1.175513
bathrooms,919.0,3.210011,1.0,2.0,3.0,4.0,7.0,1.220052
area_sqm,919.0,216.332971,38.0,127.0,164.0,230.5,4000.0,237.899047
available_from,919,2026-06-21 14:07:42.241567,2026-03-28 00:00:00,2026-06-18 00:00:00,2026-06-21 00:00:00,2026-06-22 00:00:00,2029-01-18 00:00:00,NaN
area_sqft,919.0,2328.586507,409.0,1367.0,1765.0,2481.0,43056.0,2560.736387
amenity_balcony,919.0,0.963003,0.0,1.0,1.0,1.0,1.0,0.188857
amenity_built_in_wardrobes,919.0,0.850925,0.0,1.0,1.0,1.0,1.0,0.356356
amenity_central_a_c,919.0,0.885745,0.0,1.0,1.0,1.0,1.0,0.318293
amenity_children's_pool,919.0,0.021763,0.0,0.0,0.0,0.0,1.0,0.145988
amenity_covered_parking,919.0,0.942329,0.0,1.0,1.0,1.0,1.0,0.233248
amenity_kitchen_appliances,919.0,0.829162,0.0,1.0,1.0,1.0,1.0,0.376572
amenity_lobby_in_building,919.0,0.021763,0.0,0.0,0.0,0.0,1.0,0.145988
amenity_maids_room,919.0,0.855277,0.0,1.0,1.0,1.0,1.0,0.352012
amenity_private_garden,919.0,0.849837,0.0,1.0,1.0,1.0,1.0,0.357426
amenity_private_pool,919.0,0.809576,0.0,1.0,1.0,1.0,1.0,0.39285
amenity_security,919.0,0.188248,0.0,0.0,0.0,0.0,1.0,0.391123
amenity_shared_gym,919.0,0.092492,0.0,0.0,0.0,0.0,1.0,0.289877
amenity_shared_pool,919.0,0.845484,0.0,1.0,1.0,1.0,1.0,0.361639
amenity_shared_spa,919.0,0.117519,0.0,0.0,0.0,0.0,1.0,0.322213
amenity_study,919.0,0.337323,0.0,0.0,0.0,1.0,1.0,0.473054
amenity_view_of_landmark,919.0,0.03482,0.0,0.0,0.0,0.0,1.0,0.183425
amenity_view_of_water,919.0,0.203482,0.0,0.0,0.0,0.0,1.0,0.402807
amenity_walk-in_closet,919.0,0.048966,0.0,0.0,0.0,0.0,1.0,0.215915
available_year,919.0,2026.008705,2026.0,2026.0,2026.0,2026.0,2029.0,0.154562
available_month,919.0,5.973885,1.0,6.0,6.0,6.0,6.0,0.318926
available_day,919.0,19.202394,1.0,18.0,21.0,22.0,30.0,4.146337
price_per_sqm,919.0,117836.720215,28695.652174,84580.41958,108333.333333,134833.333333,861538.461538,63624.429066
amenities_count,919.0,8.897715,1.0,9.0,9.0,9.0,10.0,1.001298
total_rooms,919.0,6.232862,2.0,4.0,6.0,7.0,14.0,2.321203
price_per_bedroom,919.0,8162009.851516,1650000.0,5000000.0,6500000.0,8800000.0,128571428.571429,8196020.959427
price_per_bathroom,919.0,7770400.546629,1650000.0,4500000.0,6000000.0,8333333.333333,128571428.571429,8211735.867959
area_per_bedroom,919.0,67.493792,30.0,51.666667,61.5,74.291667,571.428571,33.167125
area_per_bathroom,919.0,63.698518,28.333333,48.416667,58.333333,70.0,571.428571,32.812038
amenities_per_room,919.0,1.657681,0.2,1.25,1.5,2.125,5.0,0.764461